src/backend/controllers/UserController.php
<?php

namespace interPro\userModule\backend\controllers;

use Yii;
use interPro\userModule\common\models\User;
use interPro\userModule\backend\models\userSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'set-as-customer' => ['post'],
                    'set-as-admin' => ['post'],
                    'activate' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new userSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionAssign($id)
    {
        return $this->render('assign', [
            'model' => $this->findModel($id),
        ]);
    }
    
    
    /**
     * Activate a User.
     * @param integer $id
     * @return mixed
     */
    public function actionActivate($id)
    {
        $model = $this->findModel($id);
        
        $model->status = User::STATUS_ACTIVE;
        $model->save();
        $model->sendEmail(User::EMAIL_USER_ACTIVATED);
        
        return $this->redirect(['view', 'id' => $model->id]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->setScenario('create');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionSetAsAdmin($id)
    {
        $user = $this->findModel($id);
        $user->userType = User::TYPE_ADMIN;
        $user->save();

        return $this->redirect(['view', 'id' => $user->id]);
    }
    
    public function actionSetAsCustomer($id)
    {
        $user = $this->findModel($id);
        $user->userType = User::TYPE_CUSTOMER;
        $user->save();

        return $this->redirect(['view', 'id' => $user->id]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/frontend/controllers/DefaultController.php
<?php

namespace interPro\userModule\frontend\controllers;

use Yii;
use interPro\userModule\common\models\User;
use interPro\userModule\common\models\LoginForm;
use interPro\userModule\common\models\Address;
use yii\web\Controller;
use yii\filters\AccessControl;
use interPro\userModule\frontend\models\PasswordResetRequestForm;
use interPro\userModule\frontend\models\ResetPasswordForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;

/**
 * DefaultController 
 */
class DefaultController extends Controller
{
    
    public $defaultAction = 'my-account';
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['signup', 'login', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'my-account', 'address', 'update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'eauth' => [
                // required to disable csrf validation on OpenID requests
                'class' => \nodge\eauth\openid\ControllerBehavior::className(),
                'only' => ['login'],
            ],
        ];
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new User();
        $model->setScenario('register');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->getUser()->login($model)) {
                return $this->goHome();
            }
            
        } else {
            return $this->render('signup', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionLogin($service = null, $from = null)
    {
        if (!\Yii::$app->user->isGuest) {
            return $from ? $this->redirect($from) : $this->goHome();
        }

        if ($service) {
            /** @var $eauth \nodge\eauth\ServiceBase */
            $eauth = Yii::$app->get('eauth')->getIdentity($service);
            $eauth->setRedirectUrl(Yii::$app->getUser()->getReturnUrl());
            $eauth->setCancelUrl(Yii::$app->getUrlManager()->createAbsoluteUrl('/user/login'));

            try {
                if ($eauth->authenticate()) {

                    $identity = User::findByEAuth($eauth);

                    Yii::$app->getUser()->login($identity, 3600 * 24 * 30);
                    // special redirect with closing popup window
                    if (is_null($identity->email)) {
                        Yii::$app->session->setFlash('info', Yii::t('user', 'Please enter your email address.'));
                        $eauth->redirect(['/user/update', 'redirect' => $eauth->getRedirectUrl()]);
                    } else {
                        $eauth->redirect();
                    }
                }
                else {
                    // close popup window and redirect to cancelUrl
                    $eauth->cancel();
                }
            }
            catch (\nodge\eauth\ErrorException $e) {
                // save error to show it later
                Yii::$app->getSession()->setFlash('error', 'EAuthException: '.$e->getMessage());

                // close popup window and redirect to cancelUrl
                $eauth->redirect($eauth->getCancelUrl());
            }
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $from ? $this->redirect($from) : $this->goHome();
        } else {
            return $this->render('login', [
                'model' => $model,
                'from' => $from
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout(false);

        return $this->goHome();
    }
    
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', Yii::t('user','Check your email for further instructions.'));

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', Yii::t('user','Sorry, we are unable to reset password for email provided.'));
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('user','New password was saved.'));

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    
    public function actionMyAccount()
    {
        return $this->render('view', [
            'model' => $this->findModel(Yii::$app->user->getId()),
        ]);
    }
    
    public function actionUpdate($redirect = null) {
        
        $model = $this->findModel(Yii::$app->user->getId());
        $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect($redirect ? $redirect : ['my-account']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionAddress($id = null, $from = null, $type = null) {
        $model = $this->findAddressById($id);
        
        if($type) {
            $model->type = $type;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($from) {
                return $this->redirect([$from, 'type' => $model->type, 'id' => $model->id]);
            }
            
            return $this->redirect(['my-account']);
        } else {
            return $this->render('address', [
                'model' => $model,
            ]);
        }

        return $this->render('address', [
                    'model' => $model
        ]);
    }

    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            return Yii::$app->getUser()->getIdentity();
        }
    }
    
    protected function findAddressById($id) {
        if (isset($id) && ($model = Address::findOne(['idUser' => Yii::$app->user->getId(), 'id' => $id])) !== null) {
            return $model;
        } else {
            return new Address(['idUser' => Yii::$app->user->getId()]);
        }
    }
}

src/frontend/views/default/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'firstName')->textInput(['maxlength' => 100]) ?>
            <?= $form->field($model, 'lastName')->textInput(['maxlength' => 100]) ?>

            <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

            <?= $form->field($model, 'phone')->textInput(['maxlength' => 15]) ?>
        </div>
        <div class="col-md-6">
            <?php
                if (!Yii::$app->getUser()->identity->isSocialUser()) {
                    echo $form->field($model, 'password')->passwordInput(['value' => '']);

                    echo $form->field($model, 'repeatpassword')->passwordInput(['value' => '']);
                }
            ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('user', 'Register') : Yii::t('all', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/frontend/views/default/_register_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'firstName')->textInput(['maxlength' => 100]) ?>
    <?= $form->field($model, 'lastName')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model, 'phone')->textInput(['maxlength' => 15]) ?>
    
    <?= $form->field($model, 'password')->passwordInput(['value' => '']) ?>
    
    <?= $form->field($model, 'repeatpassword')->passwordInput(['value' => '']) ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('all', 'Create') : Yii::t('all', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/frontend/views/default/address.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use interPro\userModule\common\models\Address;
use interPro\userModule\common\dictionary\Countries;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\Address */
/* @var $form ActiveForm */

$this->title = $model->isNewRecord ? Yii::t('address', 'Create address') : Yii::t('address', 'Update address');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'My account'), 'url' => ['my-account']];
$this->params['breadcrumbs'][] = $this->title;
?>
<article class="user-address">

    <h1 class="green"><?= $this->title ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-4">

            <?= $form->field($model, 'type')->dropDownList(Address::getTypesList()) ?>
            <?= $form->field($model, 'nip')->label(Yii::t('address', 'Nip') . ' <small>(' . Yii::t('address', 'Required only for company') . ')</small>') ?>
            <?= $form->field($model, 'phone') ?>
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'name') ?>
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'street') ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'number') ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'apartmentNumber') ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <?= $form->field($model, 'city') ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'postCode') ?>
                </div>
                <div class="col-md-4">
                    <?=
                    $form->field($model, 'country')->widget(Select2::classname(), [
                        'data' => Countries::getCountriesWithNativeNames(),
                        'options' => ['placeholder' => Yii::t('address', 'Select country')],
                    ]);
                    $form->field($model, 'country')
                    ?>
                </div>
            </div>
        </div>


    </div>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('address', 'Submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</article><!-- user-address -->

src/frontend/views/default/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model interPro\userModule\common\models\LoginForm */

$this->title = Yii::t('user', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<article class="site-login">

    <div class="row">
        <div class="col-lg-4">
            <h1 class="green"><?= Html::encode($this->title) ?></h1>
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                <div style="color:#999;margin:1em 0">
                    <?= Yii::t('user', 'If you forgot your password you can'); ?> <?= Html::a(Yii::t('user', 'reset it'), ['/user/request-password-reset']) ?>.
                </div>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('user', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>

            <?php if (count(Yii::$app->controller->module->services)) { ?>
                <p class="lead"><?= Yii::t('user', 'Click on the logo below to log in using the service:'); ?></p>
                <?php echo \nodge\eauth\Widget::widget([
                    'action' => '/user/login',
                    'assetBundle' => 'interPro\userModule\frontend\assets\AuthWidgetAssets'
                ]); ?>
            <?php } ?>
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-6">
            <h2 class="blue"><?= Yii::t('user', 'You do not have an account yet?'); ?></h2>
            <p><?= Html::a(Yii::t('user', 'Go to register'), ['/user/signup'], [
                'class' => 'btn btn-success'
            ]); ?></p>

            <p>&nbsp;</p>
            <?php
                if (Yii::$app->controller->module->enableTemporaryUsers) {
            ?>
                <h2 class="blue"><?= Yii::t('user', 'You do not want to register?'); ?></h2>
                <p>
                    <?=
                        Html::a(Yii::t('user', 'Go shopping without registration'), [
                            '/user/temporary/create',
                            'from' => isset($from) ? $from : ''
                        ], [
                            'class' => 'btn btn-success'
                        ]);
                    ?>
                </p>
            <?php
                }
            ?>
        </div>
    </div>
</article>

src/frontend/views/default/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = Yii::t('user', 'Request password reset');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('user', 'Please fill out your email. A link to reset password will be sent there.'); ?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('user', 'Send'), ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

src/frontend/views/default/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = Yii::t('user', 'Reset password');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('user', 'Please choose your new password') ?>:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('user', 'Save'), ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

src/frontend/views/default/signup.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */

$this->title = Yii::t('user', 'Registration');
$this->params['breadcrumbs'][] = $this->title;
?>
<article class="user-create">

    <div class="row">
        <div class="col-md-4">
            <h1 class="green"><?= Html::encode($this->title) ?></h1>
            <?= $this->render('_register_form', [
                'model' => $model,
            ]) ?>
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-6">
            <h2 class="blue"><?= Yii::t('user', 'Already you have an account?'); ?></h2>
            <p><?= Html::a(Yii::t('user', 'Go to login'), Yii::getAlias('@web').'/user/login', [
                    'class' => 'btn btn-success'
                ]); ?></p>
        </div>
    </div>

</article>

src/frontend/views/default/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */

$this->title = Yii::t('user', 'Update {modelClass}: ', [
    'modelClass' => 'User',
]) . ' ' . $model->firstName . ' ' . $model->lastName;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'My account'), 'url' => ['my-account']];
$this->params['breadcrumbs'][] = Yii::t('user', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/frontend/views/default/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */

$this->title = Yii::t('user', 'My account');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
    
    <?php if (count(\Yii::$app->controller->module->userMenu)) {
    ?>
        <p class="pull-right">
            <?php foreach (\Yii::$app->controller->module->userMenu as $menu) {
                echo Html::a(is_array($menu['label']) ? Yii::t($menu['label']['category'], $menu['label']['name']) : $menu['label'], $menu['url'], ['class' => key_exists('class', $menu) ? $menu['class'] : 'btn-default btn']);
            } ?>
        </p>
    <?php
    }
    ?>
    
    <h1><?= Html::encode($this->title) ?> 
        <?= Html::a(Yii::t('user', 'Edit data'), ['/user/update'], ['class' => 'btn btn-primary']) ?>
    </h1>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'username',
            'firstName',
            'lastName',
            'email:email',
            'phone',
            'createdDate'
        ],
    ]);

    echo '<h3>' . Yii::t('user', 'Your addresses') . '</h3>';

    $dataAddressProvider = new ActiveDataProvider([
        'query' => $model->getAddresses()
    ]);

    echo GridView::widget([
        'dataProvider' => $dataAddressProvider,
        'layout' => "{items}\n{pager}",
        'columns' => [
            [
                'attribute' => 'user',
                'label' => Yii::t('user', 'Type'),
                'format' => 'html',
                'value' => function ($model) {
                    return $model->getType();
                },
            ],
            'name',
            [
                'attribute' => 'user',
                'label' => Yii::t('address', 'Address'),
                'format' => 'html',
                'value' => function ($model) {
                    return $model->getPreformatted();
                },
            ],
            'nip',
            'phone',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        $options = [
                            'title' => Yii::t('address', 'Update address'),
                            'href' => '/user/address?id=' . $model->id
                        ];

                        return Html::a('<span class="glyphicon glyphicon-edit"></span>', null, $options);
                    }
                        ]
                    ],
                ],
            ]);
            ?>
    <div class="form-group">
        <?= Html::a(Yii::t('address', 'Create address'), '/user/address', ['class' => 'btn btn-primary']) ?>
    </div>

</div>