src/common/models/User.php
<?php

namespace interPro\userModule\common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\IdentityInterface;
use interPro\userModule\common\models\Address;

/**
 * User model
 *
 * Author Tomasz Górecki <tomas.gorecki@gmail.com>
 *
 * @property integer $id
 * @property string $username
 * @property string $firstName
 * @property string $lastName
 * @property string $passwordHash
 * @property string $passwordResetToken
 * @property string $email
 * @property string $phone
 * @property string $authKey
 * @property integer $status
 * @property datatime $createdDate
 * @property datatime $updatedDate
 * @property datatime $lastLogin
 * @property string $language
 * @property integer $userType
 * @property string $socialId
 * @property string $photo
 *
 * @property Address $address
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;
    const TYPE_CUSTOMER = 1;
    const TYPE_TEMPORARY = 2;
    const TYPE_ADMIN = 9;
    const SCENARIO_SOCIAL = 'social';
    const SCENARIO_TEMPORARY = 'temporary';

    const EMAIL_USER_ACTIVATED = 'user-activated';
    const TEMPORARY_USER_KEY = 'temporaryUser';

    public $password;
    public $repeatpassword;

    /**
     * @var array EAuth attributes
     */
    public $profile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createdDate',
                'updatedAtAttribute' => 'updatedDate',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['username', 'filter', 'filter' => 'trim'],
            ['username', 'required'],
            ['username', 'unique', 'message' => Yii::t('user', 'This username has already been taken.'), 'on' => self::SCENARIO_DEFAULT],
            ['username', 'string', 'min' => 2, 'max' => 255],

            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'unique', 'filter' => ['userType' => self::TYPE_CUSTOMER], 'message' => Yii::t('user', 'This email address has already been taken.'),
                'when' => function ($model, $attribute) {
                    return $model->{$attribute} === self::TYPE_CUSTOMER;
                }],

            ['phone', 'string', 'min' => 9, 'max' => 15],
            ['phone', 'required', 'on' => [self::SCENARIO_TEMPORARY]],

            ['password', 'required', 'on' => ['register', 'create']],
            ['password', 'string', 'min' => 6],

            ['repeatpassword', 'required', 'on' => ['register', 'create']],
            ['repeatpassword', 'compare', 'compareAttribute' => 'password', 'message' => Yii::t('user', "Passwords don't match.")],

            ['userType', 'default', 'value' => self::TYPE_CUSTOMER],
            ['userType', 'in', 'range' => [self::TYPE_CUSTOMER, self::TYPE_TEMPORARY, self::TYPE_ADMIN]],

            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            ['firstName', 'required'],
            ['firstName', 'string', 'min' => 2, 'max' => 255],
            ['lastName', 'required'],
            ['lastName', 'string', 'min' => 2, 'max' => 255],
            ['socialId', 'string', 'min' => 2, 'max' => 100],
            ['socialId', 'required', 'on' => [self::SCENARIO_SOCIAL]],

            ['photo', 'string', 'min' => 2, 'max' => 500]
        ];
    }


    public function attributeLabels()
    {
        return [
            'id' => Yii::t('user', 'ID'),
            'role' => Yii::t('user', 'Role'),
            'username' => Yii::t('user', 'Username'),
            'firstName' => Yii::t('user', 'First Name'),
            'lastName' => Yii::t('user', 'Last Name'),
            'password' => Yii::t('user', 'Password'),
            'repeatpassword' => Yii::t('user', 'Repeat password'),
            'email' => Yii::t('user', 'E-mail'),
            'phone' => Yii::t('user', 'Phone'),
            'status' => Yii::t('user', 'Status'),
            'createdDate' => Yii::t('user', 'Registration date'),
            'updatedDate' => Yii::t('user', 'Last changed date'),
            'lastLogin' => Yii::t('user', 'Last login date'),
            'userType' => Yii::t('user', 'Acoount type'),
            'language' => Yii::t('user', 'Language')
        ];
    }


    /**
     * Returns a list of scenarios and the corresponding active attributes.
     * @return array
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_DEFAULT] = ['id', 'username', 'email', 'phone', 'firstName', 'lastName', 'status'];
        $scenarios['register'] = ['username', 'email', 'phone', 'firstName', 'lastName', 'password', 'repeatpassword'];
        $scenarios['create'] = ['username', 'role', 'email', 'phone', 'firstName', 'lastName', 'password', 'repeatpassword'];
        $scenarios['update'] = ['email', 'username', 'role', 'phone', 'firstName', 'lastName', 'password', 'repeatpassword', 'status'];
        $scenarios[self::SCENARIO_TEMPORARY] = ['email', 'firstName', 'lastName', 'phone', 'userType'];
        $scenarios[self::SCENARIO_SOCIAL] = ['username', 'socialId'];

        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        if (Yii::$app->getSession()->has('user-' . $id)) {
            return new self(Yii::$app->getSession()->get('user-' . $id));
        } else {
            return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
        }
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['authKey' => $token, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'socialId' => null, 'status' => self::STATUS_ACTIVE]);
    }


    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findAdminByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE, 'userType' => self::TYPE_ADMIN]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'passwordResetToken' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int)end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->passwordHash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->passwordHash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->authKey = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->passwordResetToken = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->passwordResetToken = null;
    }

    /**
     * Set last login for user.
     * @return boolean
     */
    public function setLastLogin()
    {
        $this->lastLogin = new Expression('NOW()');

        if (!$this->isNewRecord) {
            //I didn't use save() because don't wont change updateDate
            return (bool)$this->updateAttributes($this);
        } else {
            return $this;
        }
    }


src/backend/controllers/AddressController.php
<?php

namespace interPro\userModule\backend\controllers;

use Yii;
use interPro\userModule\common\models\Address;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AddressController implements the CRUD actions for Address model.
 */
class AddressController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Creates a new Address model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($idUser)
    {
        $model = new Address(['idUser' => $idUser]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['user/view', 'id' => $model->idUser]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Address model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['user/view', 'id' => $model->idUser]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Address model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $idUser = $model->idUser;
        $model->delete();

        return $this->redirect(['user/view', 'id' => $idUser]);
    }

    /**
     * Finds the Address model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Address the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Address::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/backend/controllers/UserController.php
<?php

namespace interPro\userModule\backend\controllers;

use Yii;
use interPro\userModule\common\models\User;
use interPro\userModule\backend\models\userSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'set-as-customer' => ['post'],
                    'set-as-admin' => ['post'],
                    'activate' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new userSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionAssign($id)
    {
        return $this->render('assign', [
            'model' => $this->findModel($id),
        ]);
    }
    
    
    /**
     * Activate a User.
     * @param integer $id
     * @return mixed
     */
    public function actionActivate($id)
    {
        $model = $this->findModel($id);
        
        $model->status = User::STATUS_ACTIVE;
        $model->save();
        $model->sendEmail(User::EMAIL_USER_ACTIVATED);
        
        return $this->redirect(['view', 'id' => $model->id]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->setScenario('create');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionSetAsAdmin($id)
    {
        $user = $this->findModel($id);
        $user->userType = User::TYPE_ADMIN;
        $user->save();

        return $this->redirect(['view', 'id' => $user->id]);
    }
    
    public function actionSetAsCustomer($id)
    {
        $user = $this->findModel($id);
        $user->userType = User::TYPE_CUSTOMER;
        $user->save();

        return $this->redirect(['view', 'id' => $user->id]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use interPro\userModule\common\models\User;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'username')->textInput(['maxlength' => 255]) ?>

            <?= $form->field($model, 'firstName')->textInput(['maxlength' => 100]) ?>

            <?= $form->field($model, 'lastName')->textInput(['maxlength' => 100]) ?>

            <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'phone')->textInput(['maxlength' => 15]) ?>

            <?= $form->field($model, 'status')->dropDownList(User::getStatusesList()) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'password')->passwordInput() ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'repeatpassword')->passwordInput() ?>
        </div>
    </div>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('user', 'Create') : Yii::t('user', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/backend/views/user/assign.php
<?php

/**
 * @var $model \interPro\userModule\common\models\User
 */

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */

$this->title = Yii::t('user', 'User permission');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->firstName . ' ' . $model->lastName, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
    <h1><?= $this->title ?>: <?= $model->firstName . ' ' . $model->lastName ?></h1>
<?php
echo \dektrium\rbac\widgets\Assignments::widget([
    'userId' => $model->id
]);

echo '<br>';

echo \yii\helpers\Html::a(Yii::t('user', 'Return to user view'), ['view', 'id' => $model->id], [
        'class' => 'btn btn-primary'
]);

src/backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = Yii::t('user', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use interPro\userModule\common\models\User;

/* @var $this yii\web\View */
/* @var $searchModel interPro\userModule\backend\models\userSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('user', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <p class="pull-right">
        <?= Html::a(Yii::t('user', 'Create User'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <h1><?= Html::encode($this->title) ?></h1>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\DataColumn',
                'attribute' => 'id',
                'filter' => '',
            ],
            [
                'class' => 'yii\grid\DataColumn',
                'attribute' => 'userType',
                'filter' => User::getTypesList(),
                'format' => 'html',
                'value' => function ($data) {
                    $icon = $data->userType === User::TYPE_ADMIN ? 'star' : 'user';
                    return '<span class="glyphicon glyphicon-' . $icon . '" title="' . User::getTypesList()[$data->userType] . '"></span>';
                },
            ],
            'username',
            'firstName',
            'lastName',
            'email:email',
            [
                'class' => 'yii\grid\DataColumn',
                'attribute' => 'status',
                'format' => 'raw',
                'filter' => User::getStatusesList(),
                'value' => function ($data) {
                    return User::getStatusesList()[$data->status];
                }
            ],
            'language',
            'createdDate',
            'lastLogin',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => Yii::$app->getModule('user')->rbacEnabled ? '{view} {assign} {update} {delete}' : '{view} {update} {delete}',
                'buttons' => [
                    'assign' => function ($url, $model, $key) {
                        return Html::a(Html::tag('span', '', ['class' => 'glyphicon glyphicon-wrench']), ['assign', 'id' => $model->id], [
                            'title' => Yii::t('user', 'Edit permissions'),
                            'aria-label' => Yii::t('user', 'Edit permissions'),
                        ]);
                    }
                ]
            ],
        ],
    ]); ?>

</div>

src/backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */

$this->title = Yii::t('user', 'Update {modelClass}: ', [
    'modelClass' => 'User',
]) . ' ' . $model->firstName . ' ' . $model->lastName;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->firstName . ' ' . $model->lastName, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('user', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use interPro\userModule\common\models\User;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model interPro\userModule\common\models\User */

$this->title = $model->firstName . ' ' . $model->lastName;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('user', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php

        if ($model->status !== User::STATUS_ACTIVE) {
            echo Html::a('<span class="glyphicon glyphicon-ok"></span> ' . Yii::t('user', 'User activation'), ['activate', 'id' => $model->id], [
                    'class' => 'btn btn-warning',
                    'data' => [
                        'confirm' => Yii::t('user', 'Are you sure you want to activate this user?'),
                        'method' => 'post',
                    ],
                ]) . ' ';
        }

        if ($model->userType === User::TYPE_CUSTOMER) {
            echo Html::a('<span class="glyphicon glyphicon-star"></span> ' . Yii::t('user', 'Set as admin'), ['set-as-admin', 'id' => $model->id], [
                'class' => 'btn btn-success',
                'data' => [
                    'confirm' => Yii::t('user', 'Are you sure you want to set as admin this user?'),
                    'method' => 'post',
                ],
            ]);
        } else {
            echo Html::a('<span class="glyphicon glyphicon-user"></span> ' . Yii::t('user', 'Set as customer'), ['set-as-customer', 'id' => $model->id], [
                'class' => 'btn btn-warning',
                'data' => [
                    'confirm' => Yii::t('user', 'Are you sure you want to set as customer this user?'),
                    'method' => 'post',
                ],
            ]);
        }
        ?>
        <?php
        if (Yii::$app->getModule('user')->rbacEnabled) {
            echo Html::a('<span class="glyphicon glyphicon glyphicon-wrench"></span> ' . Yii::t('user', 'Edit permissions'), ['assign', 'id' => $model->id], ['class' => 'btn btn-default']);
        }
        ?>
        <?=
        Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('user', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('user', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ])
        ?>
    </p>
    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'firstName',
            'lastName',
            'email:email',
            [
                'label' => Yii::t('all', 'Status'),
                'value' => User::getStatusesList()[$model->status]
            ],
            'language',
            'createdDate',
            'updatedDate',
            'lastLogin'
        ],
    ]);

    echo Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('address', 'Create address'), ['address/create', 'idUser' => $model->id], ['class' => 'pull-right btn btn-default']);

    echo '<h3>' . Yii::t('user', 'Addresses user') . '</h3>';

    $dataAddressProvider = new ActiveDataProvider([
        'query' => $model->getAddresses()
    ]);

    echo GridView::widget([
        'dataProvider' => $dataAddressProvider,
        'layout' => "{items}\n{pager}",
        'columns' => [
            [
                'attribute' => 'user',
                'label' => Yii::t('user', 'Type'),
                'format' => 'html',
                'value' => function ($model) {
                    return $model->getType();
                },
            ],
            'name',
            [
                'attribute' => 'user',
                'label' => Yii::t('address', 'Address'),
                'format' => 'html',
                'value' => function ($model) {
                    return $model->getPreformatted();
                },
            ],
            'nip',
            'phone',
            [
                'class' => 'yii\grid\ActionColumn',
                'controller' => 'address',
                'template' => '{update} {delete}'
            ]
        ],
    ]);
    ?>

</div>